server {
    listen 80;

    location = /cost-effectiveness/_stcore/stream {
        proxy_pass http://ui:8501/cost-effectiveness/_stcore/stream;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_read_timeout 300;
    }

    location / {
        rewrite ^(.*)$ /cost-effectiveness$1 break;
        proxy_pass http://ui:8501;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header Accept-Encoding "";
        proxy_cache_bypass $http_upgrade;
        proxy_read_timeout 300;

        sub_filter_once off;
        sub_filter_types text/html;
        sub_filter './static/' '/cost-effectiveness/static/';
        sub_filter './favicon.png' '/cost-effectiveness/favicon.png';
    }
}
