"""
Authoritative Table 2 data from the published systematic review.
Supervision mapping: yes → supervised, partly → mixed, – or NA → unknown.
Interval_type / comparator_type use the controlled vocabulary from ce_comparisons.
"""

TABLE2_CORRECTIONS = [
    # ── BACK ─────────────────────────────────────────────────────────────────
    {"a": "barker",      "y": "2019", "total_sessions": "7",  "session_length": "30-60 min", "duration_weeks": "12", "supervision": "supervised",  "intervention_type": "manual_therapy+education",    "comparator_type": "education",         "intervention_detail": "manual therapy, home stretching and education",       "comparator_detail": "1 session education by PT"},
    {"a": "barker",      "y": "2020", "total_sessions": "7",  "session_length": "30-60 min", "duration_weeks": "12", "supervision": "supervised",  "intervention_type": "exercise+education",          "comparator_type": "education",         "intervention_detail": "individual exercise therapy, home exercises and education", "comparator_detail": "1 session education by PT"},
    {"a": "muller",      "y": "2019", "frequency": "2x/week then 1x/week", "total_sessions": "36", "session_length": "60 min", "duration_weeks": "24", "supervision": "supervised",  "intervention_type": "exercise",  "comparator_type": "usual_care",        "intervention_detail": "group exercise therapy", "comparator_detail": "usual physiotherapeutic care"},
    {"a": "mueller",     "y": "2019", "frequency": "2x/week then 1x/week", "total_sessions": "36", "session_length": "60 min", "duration_weeks": "24", "supervision": "supervised",  "intervention_type": "exercise",  "comparator_type": "usual_care",        "intervention_detail": "group exercise therapy", "comparator_detail": "usual physiotherapeutic care"},
    {"a": "sogaard",     "y": "2008", "frequency": "2x/week", "total_sessions": "3",  "session_length": "90 min",    "duration_weeks": "8",  "supervision": "unknown",     "intervention_type": "exercise",            "comparator_type": "education",         "intervention_detail": "group meetings / individual exercise therapy", "comparator_detail": "oral instruction for home exercises"},
    # ── LOW BACK PAIN ─────────────────────────────────────────────────────────
    {"a": "aboagye",     "y": "2015", "frequency": "2x/week", "session_length": "unknown", "duration_weeks": "6",  "supervision": "mixed",       "intervention_type": "exercise",                    "comparator_type": "education",         "intervention_detail": "group yoga", "comparator_detail": "evidence-based self-care advice"},
    {"a": "ankjaer",     "y": "1994", "supervision": "mixed",       "intervention_type": "exercise",                    "comparator_type": "usual_care",        "intervention_detail": "group exercise therapy", "comparator_detail": "usual physiotherapeutic care"},
    {"a": "apeldoorn",   "y": "2012", "duration_weeks": "4",  "supervision": "unknown",     "intervention_type": "exercise",                    "comparator_type": "usual_care",        "intervention_detail": "stratified treatment (direction specific exercises, manipulation or stabilization)", "comparator_detail": "usual physiotherapeutic care"},
    {"a": "bello",       "y": "2015", "frequency": "2x/week", "session_length": "45 min",   "duration_weeks": "12", "supervision": "supervised",  "intervention_type": "exercise",                    "comparator_type": "usual_care",        "intervention_detail": "behavioral graded activity", "comparator_detail": "individual conventional exercise therapy"},
    {"a": "burton",      "y": "2004", "total_sessions": "9",  "duration_weeks": "12", "supervision": "mixed",       "intervention_type": "exercise+manual_therapy",     "comparator_type": "usual_care",        "intervention_detail": "group exercise therapy and spinal manipulation", "comparator_detail": "usual care in GP"},
    {"a": "canaway",     "y": "2018", "total_sessions": "2",  "session_length": "20-40 min", "supervision": "supervised",  "intervention_type": "exercise+education",          "comparator_type": "usual_care",        "intervention_detail": "individual behavior change and exercise therapy", "comparator_detail": "usual physiotherapeutic care"},
    {"a": "carr",        "y": "2005", "frequency": "2x/week", "total_sessions": "8",  "session_length": "60 min",   "duration_weeks": "4",  "supervision": "mixed",       "intervention_type": "exercise",                    "comparator_type": "usual_care",        "intervention_detail": "group exercise therapy with cognitive behavioral approach", "comparator_detail": "individual physiotherapy"},
    {"a": "cherkin",     "y": "1998", "total_sessions": "8",  "supervision": "unknown",     "intervention_type": "manual_therapy",              "comparator_type": "education",         "intervention_detail": "chiropractic or individual physical therapy (McKenzie)", "comparator_detail": "education by booklet"},
    {"a": "critchley",   "y": "2007", "total_sessions": "8",  "session_length": "30-90 min","supervision": "mixed",       "intervention_type": "exercise+education",          "comparator_type": "usual_care",        "intervention_detail": "spinal stabilization or group education with cognitive-behavioral approach", "comparator_detail": "individual physiotherapy"},
    {"a": "fritz",       "y": "2008", "total_sessions": "5",  "duration_weeks": "4",  "supervision": "unknown",     "intervention_type": "exercise",                    "comparator_type": "usual_care",        "intervention_detail": "individual physiotherapy following evidence-based guidelines", "comparator_detail": "physiotherapy not following evidence-based guidelines"},
    {"a": "fritz",       "y": "2017", "frequency": "1x/week", "total_sessions": "4",  "duration_weeks": "4",  "supervision": "unknown",     "intervention_type": "exercise+education",          "comparator_type": "usual_care",        "intervention_detail": "usual primary care, booklet and early individual physiotherapy", "comparator_detail": "usual primary care, booklet and waiting list"},
    {"a": "hahne",       "y": "2017", "frequency": "1x/week", "total_sessions": "10", "session_length": "30 min",   "duration_weeks": "10", "supervision": "mixed",       "intervention_type": "exercise+education",          "comparator_type": "education",         "intervention_detail": "individual physiotherapy and education by PT", "comparator_detail": "guideline-based education by PT and booklet"},
    {"a": "herman",      "y": "2008", "frequency": "2x/week", "session_length": "30 min",   "duration_weeks": "12", "supervision": "mixed",       "intervention_type": "mixed_physiotherapy",         "comparator_type": "education",         "intervention_detail": "naturopathic care (acupuncture, exercise, dietary advice, relaxation)", "comparator_detail": "standardized education by PT and booklet"},
    {"a": "hlobil",      "y": "2007", "frequency": "2x/week", "session_length": "60 min",   "duration_weeks": "12", "supervision": "mixed",       "intervention_type": "exercise",                    "comparator_type": "usual_care",        "intervention_detail": "Graded Activity intervention", "comparator_detail": "usual care in GP"},
    {"a": "hurley",      "y": "2015", "frequency": "1x/week", "total_sessions": "8",  "session_length": "60 min",   "duration_weeks": "8",  "supervision": "mixed",       "intervention_type": "exercise",                    "comparator_type": "usual_care",        "intervention_detail": "walking program or group exercise therapy", "comparator_detail": "usual physiotherapeutic care"},
    {"a": "johnson",     "y": "2007", "total_sessions": "8",  "session_length": "120 min",  "duration_weeks": "6",  "supervision": "mixed",       "intervention_type": "exercise+education",          "comparator_type": "education",         "intervention_detail": "cognitive behavioral therapy, group exercise therapy and home exercises", "comparator_detail": "education by booklet"},
    {"a": "karjalainen", "y": "2003", "total_sessions": "1",  "session_length": "75-90 min","supervision": "mixed",       "intervention_type": "education+exercise",          "comparator_type": "education",         "intervention_detail": "GP visit, light mobilization, graded activity exercises, leaflet", "comparator_detail": "GP visit, leaflet"},
    {"a": "kim",         "y": "2020", "frequency": "2x/week", "total_sessions": "6",  "session_length": "20 min",   "duration_weeks": "3",  "supervision": "unknown",     "intervention_type": "exercise",                    "comparator_type": "usual_care",        "intervention_detail": "individual physical therapy: ultrasound, electrotherapy, hot pack", "comparator_detail": "massage chair"},
    {"a": "niemisto",    "y": "2003", "frequency": "1x/week", "total_sessions": "4",  "session_length": "60 min",   "duration_weeks": "4",  "supervision": "mixed",       "intervention_type": "manual_therapy+exercise",     "comparator_type": "education",         "intervention_detail": "individual evaluation, manipulative treatment, exercises and booklet", "comparator_detail": "physician consultation and education by booklet"},
    {"a": "niemisto",    "y": "2005", "frequency": "1x/week", "total_sessions": "4",  "session_length": "60 min",   "duration_weeks": "4",  "supervision": "mixed",       "intervention_type": "manual_therapy+exercise",     "comparator_type": "education",         "intervention_detail": "manipulative treatment, exercises and booklet", "comparator_detail": "physician consultation and education by booklet"},
    {"a": "rivero",      "y": "2006", "total_sessions": "5",  "session_length": "30-60 min","supervision": "unknown",     "intervention_type": "exercise+education",          "comparator_type": "education",         "intervention_detail": "individual physiotherapy and education by booklet", "comparator_detail": "education by PT and booklet"},
    {"a": "smeets",      "y": "2009", "frequency": "1-3x/week","total_sessions": "20","session_length": "30-105 min","duration_weeks": "10", "supervision": "mixed",       "intervention_type": "exercise+education",          "comparator_type": "exercise",          "intervention_detail": "group and individual graded activity with problem solving", "comparator_detail": "group active physical treatment"},
    {"a": "suni",        "y": "2018", "frequency": "2x/week", "total_sessions": "32", "session_length": "45-105 min","duration_weeks": "24", "supervision": "supervised",  "intervention_type": "exercise",                    "comparator_type": "usual_care",        "intervention_detail": "group exercise therapy", "comparator_detail": "wait and see"},
    {"a": "roer",        "y": "2008", "frequency": "2x/week", "total_sessions": "46", "session_length": "30-90 min","duration_weeks": "30", "supervision": "supervised",  "intervention_type": "exercise+education",          "comparator_type": "usual_care",        "intervention_detail": "group and individual exercise therapy and back school education", "comparator_detail": "individual physiotherapy per Royal Dutch guidelines"},
    {"a": "whitehurst",  "y": "2007", "total_sessions": "7",  "session_length": "20-40 min","supervision": "mixed",       "intervention_type": "manual_therapy+exercise",     "comparator_type": "education",         "intervention_detail": "manual therapy, individual back-specific exercises, advice", "comparator_detail": "individual brief pain management (biopsychosocial model)"},
    # ── NECK ─────────────────────────────────────────────────────────────────
    {"a": "bosmans",     "y": "2011", "total_sessions": "18", "session_length": "30 min",   "supervision": "mixed",       "intervention_type": "exercise",                    "comparator_type": "other_physiotherapy",  "intervention_detail": "Behavioral Graded Activity", "comparator_detail": "manual therapy"},
    {"a": "korthals",    "y": "2003", "frequency": "1-2x/week","total_sessions": "6-12","session_length": "30-45 min","duration_weeks": "6", "supervision": "mixed",       "intervention_type": "manual_therapy",              "comparator_type": "usual_care",        "intervention_detail": "manual therapy or individual physiotherapy", "comparator_detail": "usual care in GP"},
    {"a": "leininger",   "y": "2016", "total_sessions": "24", "session_length": "60 min",   "duration_weeks": "12", "supervision": "supervised",  "intervention_type": "exercise+manual_therapy",     "comparator_type": "education",         "intervention_detail": "home exercises, advice and spinal manipulative therapy or supervised rehabilitative exercises", "comparator_detail": "home exercise and advice"},
    {"a": "lewis",       "y": "2007", "total_sessions": "6",  "session_length": "20-40 min","duration_weeks": "6",  "supervision": "mixed",       "intervention_type": "manual_therapy",              "comparator_type": "exercise",          "intervention_detail": "exercise therapy plus manual therapy or pulsed shortwave diathermy", "comparator_detail": "individual exercise therapy, advice by PT and booklet"},
    {"a": "manca",       "y": "2006", "total_sessions": "2",  "supervision": "unknown",     "intervention_type": "education",                   "comparator_type": "usual_care",        "intervention_detail": "cognitive-behavioral treatment", "comparator_detail": "usual physiotherapeutic care"},
    {"a": "dongen",      "y": "2016", "frequency": "1x/week", "total_sessions": "6",  "session_length": "30-60 min","duration_weeks": "6",  "supervision": "unknown",     "intervention_type": "manual_therapy",              "comparator_type": "exercise",          "intervention_detail": "manual therapy according to Utrecht school", "comparator_detail": "individual physiotherapy with active exercises"},
    # ── MIXED SPINE ──────────────────────────────────────────────────────────
    {"a": "denninger",   "y": "2018", "total_sessions": "7",  "supervision": "unknown",     "intervention_type": "exercise",                    "comparator_type": "usual_care",        "intervention_detail": "individual PT via direct access (back and neck program)", "comparator_detail": "initial contact by traditional medical referral"},
    {"a": "manca",       "y": "2007", "total_sessions": "3",  "supervision": "unknown",     "intervention_type": "education",                   "comparator_type": "exercise",          "intervention_detail": "individual Solution Finding Approach", "comparator_detail": "individual McKenzie therapy"},
    {"a": "skargren",    "y": "1997", "total_sessions": "6",  "supervision": "unknown",     "intervention_type": "mixed_physiotherapy",         "comparator_type": "other_physiotherapy","intervention_detail": "physiotherapy (manipulation, mobilization, McKenzie, TENS, etc.)", "comparator_detail": "chiropractic (manipulation, mobilization, traction)"},
    {"a": "skargren",    "y": "1998", "total_sessions": "5",  "supervision": "unknown",     "intervention_type": "mixed_physiotherapy",         "comparator_type": "other_physiotherapy","intervention_detail": "physiotherapy (manipulation, mobilization, McKenzie, TENS, etc.)", "comparator_detail": "chiropractic (manipulation, mobilization, traction)"},
    # ── UPPER LIMB ───────────────────────────────────────────────────────────
    {"a": "bergman",     "y": "2010", "total_sessions": "6",  "duration_weeks": "12", "supervision": "supervised",  "intervention_type": "manual_therapy",              "comparator_type": "usual_care",        "intervention_detail": "manipulative and mobilization of cervicothoracic spine and ribs", "comparator_detail": "usual care in GP"},
    {"a": "commbes",     "y": "2016", "frequency": "1x/week", "total_sessions": "8",  "session_length": "30 min",   "duration_weeks": "8",  "supervision": "supervised",  "intervention_type": "exercise+manual_therapy",     "comparator_type": "injection",         "intervention_detail": "physiotherapy (manual therapy, exercise, home exercises)", "comparator_detail": "saline or corticosteroid injection"},
    {"a": "coombes",     "y": "2016", "frequency": "1x/week", "total_sessions": "8",  "session_length": "30 min",   "duration_weeks": "8",  "supervision": "supervised",  "intervention_type": "exercise+manual_therapy",     "comparator_type": "injection",         "intervention_detail": "physiotherapy (manual therapy, exercise, home exercises)", "comparator_detail": "saline or corticosteroid injection"},
    {"a": "fernandez",   "y": "2019", "frequency": "1x/week", "total_sessions": "3",  "session_length": "30 min",   "duration_weeks": "3",  "supervision": "supervised",  "intervention_type": "manual_therapy+education",   "comparator_type": "surgery",           "intervention_detail": "manual therapy and education for exercises", "comparator_detail": "open or endoscopic surgery and education"},
    {"a": "penjas",      "y": "2019", "frequency": "1x/week", "total_sessions": "3",  "session_length": "30 min",   "duration_weeks": "3",  "supervision": "supervised",  "intervention_type": "manual_therapy+education",   "comparator_type": "surgery",           "intervention_detail": "manual therapy and education for exercises", "comparator_detail": "open or endoscopic surgery and education"},
    {"a": "geraets",     "y": "2006", "total_sessions": "18", "session_length": "60 min",   "duration_weeks": "12", "supervision": "supervised",  "intervention_type": "exercise",                    "comparator_type": "usual_care",        "intervention_detail": "group graded exercise therapy", "comparator_detail": "usual care in GP"},
    {"a": "hopewell",    "y": "2021", "total_sessions": "6",  "session_length": "20-60 min","duration_weeks": "16", "supervision": "mixed",       "intervention_type": "exercise",                    "comparator_type": "education",         "intervention_detail": "individual exercise therapy (progressive loading)", "comparator_detail": "best-practice advice by PT, education by booklet and home exercises"},
    {"a": "james",       "y": "2005", "total_sessions": "8",  "session_length": "20 min",   "duration_weeks": "6",  "supervision": "unknown",     "intervention_type": "exercise",                    "comparator_type": "injection",         "intervention_detail": "individual physiotherapy", "comparator_detail": "corticosteroid injection into subacromial space"},
    {"a": "korthals",    "y": "2004", "frequency": "2x/week", "total_sessions": "9",  "session_length": "30 min",   "duration_weeks": "6",  "supervision": "mixed",       "intervention_type": "exercise",                    "comparator_type": "injection",         "intervention_detail": "physiotherapy (ultrasound, deep friction massage, exercise)", "comparator_detail": "corticosteroid injections or wait-and-see"},
    {"a": "struijs",     "y": "2006", "total_sessions": "9",  "session_length": "30 min",   "duration_weeks": "6",  "supervision": "supervised",  "intervention_type": "exercise",                    "comparator_type": "other_physiotherapy","intervention_detail": "individual physiotherapy (ultrasound, friction massage, home exercises)", "comparator_detail": "brace with 1 initial PT visit for instruction"},
    # ── HIP ──────────────────────────────────────────────────────────────────
    {"a": "fusco",       "y": "2019", "frequency": "2x/day",  "duration_weeks": "10", "supervision": "mixed",       "intervention_type": "exercise",                    "comparator_type": "exercise",          "intervention_detail": "individual physiotherapy without hip precautions and home exercises", "comparator_detail": "individual physiotherapy with hip precautions and home exercises"},
    {"a": "griffin",     "y": "2022", "total_sessions": "8",  "session_length": "30 min",   "duration_weeks": "18", "supervision": "supervised",  "intervention_type": "surgery",                     "comparator_type": "exercise+education","intervention_detail": "hip arthroscopy", "comparator_detail": "best conservative care (personalized hip therapy: education and exercise therapy)"},
    {"a": "juhakoski",   "y": "2011", "frequency": "1x/week", "total_sessions": "12", "session_length": "45-60 min","duration_weeks": "12", "supervision": "mixed",       "intervention_type": "exercise+education",          "comparator_type": "usual_care",        "intervention_detail": "group exercise therapy and education by physician", "comparator_detail": "usual care in GP and education by physician"},
    {"a": "tan",         "y": "2016", "frequency": "1x/week", "total_sessions": "15", "duration_weeks": "12", "supervision": "unknown",     "intervention_type": "exercise",                    "comparator_type": "usual_care",        "intervention_detail": "individual exercise therapy", "comparator_detail": "usual care in GP"},
    # ── KNEE ─────────────────────────────────────────────────────────────────
    {"a": "barton",      "y": "2009", "total_sessions": "6",  "duration_weeks": "96", "supervision": "mixed",       "intervention_type": "exercise",                    "comparator_type": "education",         "intervention_detail": "quadriceps strengthening home exercises with PT visits", "comparator_detail": "education by leaflet"},
    {"a": "bennell",     "y": "2016", "frequency": "1x/week", "total_sessions": "10", "session_length": "25-70 min","duration_weeks": "12", "supervision": "mixed",       "intervention_type": "exercise+education",          "comparator_type": "exercise",          "intervention_detail": "individual education (pain coping) and exercise therapy and home program", "comparator_detail": "exercise therapy and home program only"},
    {"a": "eggerding",   "y": "2021", "supervision": "unknown",     "intervention_type": "surgery",                     "comparator_type": "exercise",          "intervention_detail": "early ACL reconstruction followed by individual physical therapy", "comparator_detail": "supervised individual physical therapy program, then optional reconstruction"},
    {"a": "ho",          "y": "2022", "total_sessions": "6",  "supervision": "mixed",       "intervention_type": "exercise+education",          "comparator_type": "medical_care",      "intervention_detail": "primary access to individual PT (education, exercise, pain treatment) and group treatment", "comparator_detail": "primary access to physician (education, medical prescription, referrals)"},
    {"a": "huang",       "y": "2012", "frequency": "daily",   "session_length": "40 min",   "duration_weeks": "4",  "supervision": "home-based",  "intervention_type": "exercise+education",          "comparator_type": "usual_care",        "intervention_detail": "home exercises and education before replacement by PT and booklet", "comparator_detail": "conventional pre-TKA care"},
    {"a": "hurley",      "y": "2007", "frequency": "2x/week", "total_sessions": "12", "session_length": "15-20 min","duration_weeks": "6",  "supervision": "mixed",       "intervention_type": "exercise+education",          "comparator_type": "usual_care",        "intervention_detail": "ESCAPE program (exercise and self-management education)", "comparator_detail": "usual primary care"},
    {"a": "hurley",      "y": "2012", "frequency": "2x/week", "total_sessions": "12", "session_length": "15-20 min","duration_weeks": "6",  "supervision": "mixed",       "intervention_type": "exercise+education",          "comparator_type": "usual_care",        "intervention_detail": "group rehabilitation program", "comparator_detail": "usual primary care"},
    {"a": "jessep",      "y": "2009", "frequency": "2x/week", "total_sessions": "10", "session_length": "60 min",   "duration_weeks": "5",  "supervision": "mixed",       "intervention_type": "exercise+education",          "comparator_type": "usual_care",        "intervention_detail": "adapted ESCAPE program (exercise and self-management education)", "comparator_detail": "usual care by PT (exercise, advice, electrotherapy, manual therapy)"},
    {"a": "kigozi",      "y": "2018", "total_sessions": "6",  "duration_weeks": "12", "supervision": "mixed",       "intervention_type": "exercise",                    "comparator_type": "usual_care",        "intervention_detail": "individual exercise program or targeted exercise adherence", "comparator_detail": "usual physiotherapeutic care"},
    {"a": "knoop",       "y": "2023", "total_sessions": "10", "duration_weeks": "12", "supervision": "unknown",     "intervention_type": "exercise",                    "comparator_type": "exercise",          "intervention_detail": "stratified exercise therapy", "comparator_detail": "usual exercise therapy by PT"},
    {"a": "mccarthy",    "y": "2004", "frequency": "2x/week", "total_sessions": "16", "session_length": "45 min",   "duration_weeks": "8",  "supervision": "supervised",  "intervention_type": "exercise+education",          "comparator_type": "education",         "intervention_detail": "group exercise therapy and home exercises with education by PT", "comparator_detail": "education by PT based on Arthritis Research Campaign booklet"},
    {"a": "mitchell",    "y": "2005", "total_sessions": "9",  "supervision": "home-based",  "intervention_type": "exercise",                    "comparator_type": "exercise",          "intervention_detail": "individual physiotherapy at home pre- and post-TKA", "comparator_detail": "individual physiotherapy and group exercise therapy post-TKA only"},
    {"a": "pryymachenko","y": "2021", "total_sessions": "12", "duration_weeks": "52", "supervision": "mixed",       "intervention_type": "exercise+manual_therapy",     "comparator_type": "exercise",          "intervention_detail": "individual exercise therapy and manual therapy with booster session", "comparator_detail": "individual exercise therapy"},
    {"a": "pryymachebko","y": "2021", "total_sessions": "12", "duration_weeks": "52", "supervision": "mixed",       "intervention_type": "exercise+manual_therapy",     "comparator_type": "exercise",          "intervention_detail": "individual exercise therapy and manual therapy with booster session", "comparator_detail": "individual exercise therapy"},
    {"a": "rhon",        "y": "2022", "total_sessions": "11", "session_length": "60 min",   "duration_weeks": "36", "supervision": "supervised",  "intervention_type": "exercise+manual_therapy",     "comparator_type": "injection",         "intervention_detail": "physical therapy (exercises, joint mobilization)", "comparator_detail": "glucocorticoid injection"},
    {"a": "sevick",      "y": "2000", "frequency": "3x/week initially", "session_length": "60 min", "duration_weeks": "72", "supervision": "mixed",       "intervention_type": "exercise",            "comparator_type": "education",         "intervention_detail": "aerobic or resistance exercise training (3 months group, 15 months home-based)", "comparator_detail": "health education"},
    {"a": "sevick",      "y": "2009", "frequency": "3x/week", "session_length": "60 min",   "duration_weeks": "72", "supervision": "mixed",       "intervention_type": "exercise+education",          "comparator_type": "exercise",          "intervention_detail": "group and individual exercise therapy and diet", "comparator_detail": "healthy lifestyle control"},
    {"a": "stan",        "y": "2015", "frequency": "2x/day",  "total_sessions": "10", "session_length": "30 min",   "duration_weeks": "1",  "supervision": "unknown",     "intervention_type": "exercise",                    "comparator_type": "surgery",           "intervention_detail": "individual rehabilitation program", "comparator_detail": "total knee arthroplasty"},
    {"a": "tan",         "y": "2010", "total_sessions": "9",  "duration_weeks": "6",  "supervision": "unknown",     "intervention_type": "exercise+education",          "comparator_type": "education",         "intervention_detail": "individual exercise therapy and home exercises", "comparator_detail": "education by a physician"},
    {"a": "tan",         "y": "2009", "total_sessions": "9",  "duration_weeks": "6",  "supervision": "unknown",     "intervention_type": "exercise+education",          "comparator_type": "education",         "intervention_detail": "individual exercise therapy and home exercises", "comparator_detail": "education by a physician"},
    {"a": "graaf",       "y": "2020", "frequency": "2x/week", "total_sessions": "16", "session_length": "30 min",   "duration_weeks": "8",  "supervision": "supervised",  "intervention_type": "exercise",                    "comparator_type": "surgery",           "intervention_detail": "individual physiotherapy and home exercises", "comparator_detail": "arthroscopic partial meniscectomy"},
    {"a": "graaff",      "y": "2023", "supervision": "mixed",       "intervention_type": "exercise",                    "comparator_type": "surgery",           "intervention_detail": "exercise programme and home exercises", "comparator_detail": "arthroscopic partial meniscectomy"},
    # ── LOWER LIMB MIXED ─────────────────────────────────────────────────────
    {"a": "abbott",      "y": "2019", "total_sessions": "9",  "session_length": "50 min",   "duration_weeks": "54", "supervision": "mixed",       "intervention_type": "exercise",                    "comparator_type": "usual_care",        "intervention_detail": "individual exercise therapy or manual therapy", "comparator_detail": "usual care in GP"},
    {"a": "pinto",       "y": "2013", "total_sessions": "9",  "session_length": "50 min",   "duration_weeks": "54", "supervision": "mixed",       "intervention_type": "exercise+manual_therapy",     "comparator_type": "usual_care",        "intervention_detail": "individual exercise therapy, manual therapy, or combined", "comparator_detail": "usual care in GP"},
    {"a": "bulthuis",    "y": "2008", "frequency": "2x/day",  "session_length": "75 min",   "duration_weeks": "3",  "supervision": "mixed",       "intervention_type": "exercise+education",          "comparator_type": "usual_care",        "intervention_detail": "individual and group exercise therapy and education by PT", "comparator_detail": "usual PT-care"},
    {"a": "coupe",       "y": "2007", "total_sessions": "25", "duration_weeks": "12", "supervision": "mixed",       "intervention_type": "exercise",                    "comparator_type": "usual_care",        "intervention_detail": "individual exercise therapy and booster session", "comparator_detail": "usual physiotherapeutic care"},
    {"a": "fernandes",   "y": "2017", "frequency": "2x/week", "total_sessions": "16", "session_length": "60 min",   "duration_weeks": "8",  "supervision": "mixed",       "intervention_type": "exercise+education",          "comparator_type": "education",         "intervention_detail": "group neuromuscular exercise program and education by PT before surgery", "comparator_detail": "standard preoperative information by leaflet"},
    {"a": "lin",         "y": "2008", "frequency": "2x/week", "total_sessions": "10", "duration_weeks": "4",  "supervision": "supervised",  "intervention_type": "exercise+manual_therapy",     "comparator_type": "exercise",          "intervention_detail": "individual physiotherapy and manual therapy", "comparator_detail": "individual physiotherapy"},
    # ── OTHER CONDITIONS ─────────────────────────────────────────────────────
    {"a": "barnhoorn",   "y": "2018", "total_sessions": "5",  "session_length": "40 min",   "supervision": "unknown",     "intervention_type": "exercise",                    "comparator_type": "usual_care",        "intervention_detail": "individual pain exposure physical therapy", "comparator_detail": "usual physiotherapeutic care"},
    {"a": "daker",       "y": "1999", "supervision": "unknown",     "intervention_type": "other_physiotherapy",        "comparator_type": "other",             "intervention_detail": "treatment by PT (orthopedic specialist)", "comparator_detail": "treatment by orthopedic surgeons"},
    {"a": "heij",        "y": "2022", "total_sessions": "15", "session_length": "30 min",   "supervision": "mixed",       "intervention_type": "exercise",                    "comparator_type": "usual_care",        "intervention_detail": "physical therapy (Coach2move)", "comparator_detail": "usual physiotherapeutic care"},
    {"a": "lilje",       "y": "2014", "frequency": "1x/week", "total_sessions": "5",  "session_length": "30-45 min","duration_weeks": "5",  "supervision": "unknown",     "intervention_type": "manual_therapy",              "comparator_type": "other",             "intervention_detail": "manual therapy", "comparator_detail": "standard care of orthopedic surgeons"},
    {"a": "hout",        "y": "2005", "frequency": "2x/week", "total_sessions": "60", "session_length": "75 min",   "duration_weeks": "104","supervision": "mixed",       "intervention_type": "exercise",                    "comparator_type": "usual_care",        "intervention_detail": "group exercise therapy (RAPIT program: weight bearing)", "comparator_detail": "usual care in GP (individual physiotherapy if necessary)"},
]

# Fields that can be patched from Table 2
TABLE2_FIELDS = [
    "frequency", "total_sessions", "session_length", "duration_weeks",
    "supervision", "intervention_type", "comparator_type",
    "intervention_detail", "comparator_detail",
]

UNKNOWN_VALS = {"unknown", "unclear", "", "none", "n/a", None}
