"""
Authoritative Table 1 data from the published systematic review.
Used for both patching the DB and validating extraction quality.
Each entry maps (author_keyword, year) → correct field values.
"""

CORRECTIONS = [
    # ── SPINE: Back (non-LBP) ─────────────────────────────────────────────
    {"a": "barker",     "y": "2019", "body_region": "low_back",    "condition": "osteoporotic vertebral fracture",        "country": "UK",          "study_design": "RCT", "perspective": "societal",   "outcome_measure": "QALY (EQ-5D)",                   "outcome_type": "QALY",     "time_horizon": "12 months"},
    {"a": "barker",     "y": "2020", "body_region": "low_back",    "condition": "osteoporotic vertebral fracture",        "country": "UK",          "study_design": "RCT", "perspective": "societal",   "outcome_measure": "QALY (EQ-5D)",                   "outcome_type": "QALY",     "time_horizon": "12 months"},
    {"a": "muller",     "y": "2019", "body_region": "low_back",    "condition": "back pain",                             "country": "Germany",     "study_design": "cohort","perspective": "healthcare","outcome_measure": "Graded chronic back pain status", "outcome_type": "clinical", "time_horizon": "24 months"},
    {"a": "mueller",    "y": "2019", "body_region": "low_back",    "condition": "back pain",                             "country": "Germany",     "study_design": "cohort","perspective": "healthcare","outcome_measure": "Graded chronic back pain status", "outcome_type": "clinical", "time_horizon": "24 months"},
    {"a": "sogaard",    "y": "2008", "body_region": "low_back",    "condition": "lumbar spinal fusion",                  "country": "Denmark",     "study_design": "RCT", "perspective": "societal",   "outcome_measure": "Pain and disability index",       "outcome_type": "clinical", "time_horizon": "24 months"},
    # ── LOW BACK PAIN ─────────────────────────────────────────────────────
    {"a": "aboagye",    "y": "2015", "body_region": "low_back",    "condition": "LBP",                                   "country": "Sweden",      "study_design": "RCT", "perspective": "societal",   "outcome_measure": "QALY (EQ-5D)",                   "outcome_type": "QALY",     "time_horizon": "12 months"},
    {"a": "ankjaer",    "y": "1994", "body_region": "low_back",    "condition": "LBP (herniated disc)",                  "country": "Denmark",     "study_design": "retrospective cohort","perspective": "societal","outcome_measure": "Low back pain rating scale","outcome_type": "clinical","time_horizon": "12 months"},
    {"a": "apeldoorn",  "y": "2012", "body_region": "low_back",    "condition": "LBP (chronic)",                         "country": "Netherlands", "study_design": "RCT", "perspective": "societal",   "outcome_measure": "QALY (EQ-5D)",                   "outcome_type": "QALY",     "time_horizon": "12 months"},
    {"a": "bello",      "y": "2015", "body_region": "low_back",    "condition": "LBP (chronic)",                         "country": "Ghana",       "study_design": "feasibility study","perspective": "healthcare","outcome_measure": "SF-36, NRS",            "outcome_type": "clinical", "time_horizon": "3 months"},
    {"a": "burton",     "y": "2004", "body_region": "low_back",    "condition": "LBP (non-specific)",                    "country": "UK",          "study_design": "RCT", "perspective": "healthcare", "outcome_measure": "QALY (EQ-5D)",                   "outcome_type": "QALY",     "time_horizon": "12 months"},
    {"a": "canaway",    "y": "2018", "body_region": "low_back",    "condition": "LBP",                                   "country": "Israel",      "study_design": "prospective cohort","perspective": "healthcare","outcome_measure": "QALY (SF-12)",           "outcome_type": "QALY",     "time_horizon": "12 months"},
    {"a": "carr",       "y": "2005", "body_region": "low_back",    "condition": "LBP",                                   "country": "UK",          "study_design": "RCT", "perspective": "healthcare", "outcome_measure": "RMDQ",                           "outcome_type": "clinical", "time_horizon": "12 months"},
    {"a": "cherkin",    "y": "1998", "body_region": "low_back",    "condition": "LBP (chronic)",                         "country": "US",          "study_design": "RCT", "perspective": "healthcare", "outcome_measure": "Bothersomeness of symptoms, RDS","outcome_type": "clinical", "time_horizon": "12-24 months"},
    {"a": "critchley",  "y": "2007", "body_region": "low_back",    "condition": "LBP (acute)",                           "country": "UK",          "study_design": "RCT", "perspective": "healthcare", "outcome_measure": "QALY (EQ-5D)",                   "outcome_type": "QALY",     "time_horizon": "18 months"},
    {"a": "fritz",      "y": "2008", "body_region": "low_back",    "condition": "LBP (acute)",                           "country": "US",          "study_design": "case-control","perspective": "healthcare","outcome_measure": "OSW, pain rating",           "outcome_type": "clinical", "time_horizon": "24 months"},
    {"a": "fritz",      "y": "2017", "body_region": "low_back",    "condition": "LBP",                                   "country": "US",          "study_design": "RCT", "perspective": "societal",   "outcome_measure": "QALY (EQ-5D)",                   "outcome_type": "QALY",     "time_horizon": "12 months"},
    {"a": "hahne",      "y": "2017", "body_region": "low_back",    "condition": "LBP (chronic)",                         "country": "Australia",   "study_design": "RCT", "perspective": "healthcare", "outcome_measure": "QALY (EQ-5D)",                   "outcome_type": "QALY",     "time_horizon": "12 months"},
    {"a": "herman",     "y": "2008", "body_region": "low_back",    "condition": "LBP",                                   "country": "US",          "study_design": "RCT", "perspective": "societal",   "outcome_measure": "QALY (SF-6D)",                   "outcome_type": "QALY",     "time_horizon": "6 months"},
    {"a": "hlobil",     "y": "2007", "body_region": "low_back",    "condition": "LBP (chronic)",                         "country": "Netherlands", "study_design": "RCT", "perspective": "societal",   "outcome_measure": "Lost productivity days",          "outcome_type": "clinical", "time_horizon": "36 months"},
    {"a": "hurley",     "y": "2015", "body_region": "low_back",    "condition": "LBP",                                   "country": "Ireland",     "study_design": "RCT", "perspective": "healthcare", "outcome_measure": "QALY (EQ-5D)",                   "outcome_type": "QALY",     "time_horizon": "12 months"},
    {"a": "johnson",    "y": "2007", "body_region": "low_back",    "condition": "LBP",                                   "country": "UK",          "study_design": "RCT", "perspective": "healthcare", "outcome_measure": "QALY (EQ-5D)",                   "outcome_type": "QALY",     "time_horizon": "12 months"},
    {"a": "karjalainen","y": "2003", "body_region": "low_back",    "condition": "LBP",                                   "country": "Finland",     "study_design": "RCT", "perspective": "healthcare", "outcome_measure": "Pain intensity, ODI, VAS",        "outcome_type": "clinical", "time_horizon": "12 months"},
    {"a": "kim",        "y": "2020", "body_region": "low_back",    "condition": "LBP (chronic)",                         "country": "South Korea", "study_design": "RCT", "perspective": "healthcare", "outcome_measure": "Functional rating index, VAS",   "outcome_type": "clinical", "time_horizon": "3 weeks"},
    {"a": "niemisto",   "y": "2003", "body_region": "low_back",    "condition": "LBP (subacute and chronic)",            "country": "Finland",     "study_design": "RCT", "perspective": "societal",   "outcome_measure": "VAS",                            "outcome_type": "clinical", "time_horizon": "12 months"},
    {"a": "niemisto",   "y": "2005", "body_region": "low_back",    "condition": "LBP (subacute and chronic)",            "country": "Finland",     "study_design": "RCT", "perspective": "societal",   "outcome_measure": "ODI, VAS",                       "outcome_type": "clinical", "time_horizon": "24 months"},
    {"a": "rivero",     "y": "2006", "body_region": "low_back",    "condition": "LBP (chronic)",                         "country": "UK",          "study_design": "RCT", "perspective": "societal",   "outcome_measure": "QALY (EQ-5D)",                   "outcome_type": "QALY",     "time_horizon": "12 months"},
    {"a": "smeets",     "y": "2009", "body_region": "low_back",    "condition": "LBP",                                   "country": "Netherlands", "study_design": "RCT", "perspective": "societal",   "outcome_measure": "RMDQ, QALY (EQ-5D)",             "outcome_type": "both",     "time_horizon": "12 months"},
    {"a": "suni",       "y": "2018", "body_region": "low_back",    "condition": "LBP (chronic)",                         "country": "Finland",     "study_design": "RCT", "perspective": "healthcare", "outcome_measure": "QALY (SF-6D)",                   "outcome_type": "QALY",     "time_horizon": "12 months"},
    {"a": "roer",       "y": "2008", "body_region": "low_back",    "condition": "LBP",                                   "country": "Netherlands", "study_design": "RCT", "perspective": "societal",   "outcome_measure": "EQ-5D, RMDQ",                    "outcome_type": "both",     "time_horizon": "12 months"},
    {"a": "whitehurst", "y": "2007", "body_region": "low_back",    "condition": "LBP (chronic)",                         "country": "UK",          "study_design": "RCT", "perspective": "healthcare", "outcome_measure": "RMDQ, QALY (EQ-5D)",             "outcome_type": "both",     "time_horizon": "12 months"},
    # ── NECK ──────────────────────────────────────────────────────────────
    {"a": "bosmans",    "y": "2011", "body_region": "neck",        "condition": "neck pain (subacute)",                  "country": "Netherlands", "study_design": "RCT", "perspective": "societal",   "outcome_measure": "Patient perceived recovery, QALY (SF-6D)","outcome_type": "both","time_horizon": "12 months"},
    {"a": "korthals",   "y": "2003", "body_region": "neck",        "condition": "neck pain",                             "country": "Netherlands", "study_design": "RCT", "perspective": "societal",   "outcome_measure": "EQ, functional disability, pain intensity","outcome_type": "both","time_horizon": "12 months"},
    {"a": "leininger",  "y": "2016", "body_region": "neck",        "condition": "neck pain (chronic)",                   "country": "US",          "study_design": "RCT", "perspective": "societal",   "outcome_measure": "QALY (SF-6D)",                   "outcome_type": "QALY",     "time_horizon": "12 months"},
    {"a": "lewis",      "y": "2007", "body_region": "neck",        "condition": "neck disorders (non-specific)",         "country": "UK",          "study_design": "RCT", "perspective": "societal",   "outcome_measure": "NPQ, QALY (EQ-5D)",              "outcome_type": "both",     "time_horizon": "6 months"},
    {"a": "manca",      "y": "2006", "body_region": "neck",        "condition": "neck pain",                             "country": "UK",          "study_design": "RCT", "perspective": "healthcare", "outcome_measure": "QALY (EQ-5D)",                   "outcome_type": "QALY",     "time_horizon": "12 months"},
    {"a": "dongen",     "y": "2016", "body_region": "neck",        "condition": "neck pain (subacute and chronic)",      "country": "Netherlands", "study_design": "RCT", "perspective": "societal",   "outcome_measure": "NDI, patient perceived recovery", "outcome_type": "clinical", "time_horizon": "12 months"},
    # ── MIXED SPINE ───────────────────────────────────────────────────────
    {"a": "denninger",  "y": "2018", "body_region": "multi_region","condition": "back or neck pain",                     "country": "US",          "study_design": "retrospective cohort","perspective": "healthcare","outcome_measure": "EQ-5D, NPRS, ODI/NDI","outcome_type": "both","time_horizon": "24 months"},
    {"a": "manca",      "y": "2007", "body_region": "multi_region","condition": "back or neck pain",                     "country": "UK",          "study_design": "RCT", "perspective": "healthcare", "outcome_measure": "QALY (EQ-5D)",                   "outcome_type": "QALY",     "time_horizon": "12 months"},
    {"a": "skargren",   "y": "1997", "body_region": "multi_region","condition": "back or neck pain",                     "country": "Sweden",      "study_design": "RCT", "perspective": "healthcare", "outcome_measure": "General health, ODS, VAS",        "outcome_type": "clinical", "time_horizon": "6 months"},
    {"a": "skargren",   "y": "1998", "body_region": "multi_region","condition": "back or neck pain",                     "country": "Sweden",      "study_design": "RCT", "perspective": "healthcare", "outcome_measure": "General health, ODS, VAS",        "outcome_type": "clinical", "time_horizon": "12 months"},
    # ── UPPER LIMB ────────────────────────────────────────────────────────
    {"a": "bergman",    "y": "2010", "body_region": "shoulder",    "condition": "shoulder complaints",                   "country": "Netherlands", "study_design": "RCT", "perspective": "societal",   "outcome_measure": "Patient perceived recovery",      "outcome_type": "clinical", "time_horizon": "6 months"},
    {"a": "commbes",    "y": "2016", "body_region": "elbow",       "condition": "epicondylitis lateralis",               "country": "Australia",   "study_design": "RCT", "perspective": "societal",   "outcome_measure": "QALY (EQ-5D)",                   "outcome_type": "QALY",     "time_horizon": "12 months"},
    {"a": "coombes",    "y": "2016", "body_region": "elbow",       "condition": "epicondylitis lateralis",               "country": "Australia",   "study_design": "RCT", "perspective": "societal",   "outcome_measure": "QALY (EQ-5D)",                   "outcome_type": "QALY",     "time_horizon": "12 months"},
    {"a": "fernandez",  "y": "2019", "body_region": "wrist",       "condition": "carpal tunnel syndrome",                "country": "Spain",       "study_design": "RCT", "perspective": "societal",   "outcome_measure": "QALY (EQ-5D)",                   "outcome_type": "QALY",     "time_horizon": "12 months"},
    {"a": "penjas",     "y": "2019", "body_region": "wrist",       "condition": "carpal tunnel syndrome",                "country": "Spain",       "study_design": "RCT", "perspective": "societal",   "outcome_measure": "QALY (EQ-5D)",                   "outcome_type": "QALY",     "time_horizon": "12 months"},
    {"a": "geraets",    "y": "2006", "body_region": "shoulder",    "condition": "shoulder complaints (chronic)",         "country": "Netherlands", "study_design": "RCT", "perspective": "societal",   "outcome_measure": "EQ-5D, SDQ",                     "outcome_type": "both",     "time_horizon": "12 months"},
    {"a": "hopewell",   "y": "2021", "body_region": "shoulder",    "condition": "rotator cuff disease",                  "country": "UK",          "study_design": "RCT", "perspective": "healthcare", "outcome_measure": "QALY (EQ-5D)",                   "outcome_type": "QALY",     "time_horizon": "12 months"},
    {"a": "james",      "y": "2005", "body_region": "shoulder",    "condition": "shoulder pain",                         "country": "UK",          "study_design": "RCT", "perspective": "healthcare", "outcome_measure": "Disability score, EQ-5D",         "outcome_type": "both",     "time_horizon": "6 months"},
    {"a": "korthals",   "y": "2004", "body_region": "elbow",       "condition": "epicondylitis lateralis",               "country": "Netherlands", "study_design": "RCT", "perspective": "societal",   "outcome_measure": "EQ, pain-free function",          "outcome_type": "both",     "time_horizon": "12 months"},
    {"a": "struijs",    "y": "2006", "body_region": "elbow",       "condition": "epicondylitis lateralis",               "country": "Netherlands", "study_design": "RCT", "perspective": "societal",   "outcome_measure": "EQ, pain-free function questionnaire","outcome_type": "both","time_horizon": "12 months"},
    # ── HIP ───────────────────────────────────────────────────────────────
    {"a": "fusco",      "y": "2019", "body_region": "hip",         "condition": "hip replacement",                       "country": "UK",          "study_design": "RCT", "perspective": "healthcare", "outcome_measure": "QALY (EQ-5D)",                   "outcome_type": "QALY",     "time_horizon": "12 months"},
    {"a": "griffin",    "y": "2022", "body_region": "hip",         "condition": "femoroacetabular impingement syndrome",  "country": "UK",          "study_design": "RCT", "perspective": "societal",   "outcome_measure": "QALY (EQ-5D)",                   "outcome_type": "QALY",     "time_horizon": "12 months"},
    {"a": "juhakoski",  "y": "2011", "body_region": "hip",         "condition": "hip osteoarthritis",                    "country": "Finland",     "study_design": "RCT", "perspective": "healthcare", "outcome_measure": "SF-36, WOMAC",                   "outcome_type": "clinical", "time_horizon": "24 months"},
    {"a": "tan",        "y": "2016", "body_region": "hip",         "condition": "hip osteoarthritis",                    "country": "Netherlands", "study_design": "RCT", "perspective": "societal",   "outcome_measure": "QALY (EQ-5D)",                   "outcome_type": "QALY",     "time_horizon": "12 months"},
    # ── KNEE ──────────────────────────────────────────────────────────────
    {"a": "barton",     "y": "2009", "body_region": "knee",        "condition": "knee pain",                             "country": "UK",          "study_design": "RCT", "perspective": "healthcare", "outcome_measure": "QALY (EQ-5D)",                   "outcome_type": "QALY",     "time_horizon": "24 months"},
    {"a": "bennell",    "y": "2016", "body_region": "knee",        "condition": "knee osteoarthritis",                   "country": "Australia",   "study_design": "RCT", "perspective": "healthcare", "outcome_measure": "QALY (EQ-5D)",                   "outcome_type": "QALY",     "time_horizon": "12 months"},
    {"a": "eggerding",  "y": "2021", "body_region": "knee",        "condition": "ACL tear",                              "country": "Netherlands", "study_design": "RCT", "perspective": "societal",   "outcome_measure": "QALY (EQ-5D)",                   "outcome_type": "QALY",     "time_horizon": "24 months"},
    {"a": "ho",         "y": "2022", "body_region": "knee",        "condition": "knee osteoarthritis",                   "country": "Sweden",      "study_design": "RCT", "perspective": "societal",   "outcome_measure": "QALY (EQ-5D)",                   "outcome_type": "QALY",     "time_horizon": "12 months"},
    {"a": "huang",      "y": "2012", "body_region": "knee",        "condition": "total knee replacement",                 "country": "Taiwan",      "study_design": "RCT", "perspective": "healthcare", "outcome_measure": "Knee ROM, LOS, VAS",              "outcome_type": "clinical", "time_horizon": "5 days"},
    {"a": "hurley",     "y": "2007", "body_region": "knee",        "condition": "knee pain (chronic)",                   "country": "UK",          "study_design": "RCT", "perspective": "healthcare", "outcome_measure": "WOMAC, QALY (EQ-5D)",             "outcome_type": "both",     "time_horizon": "6 months"},
    {"a": "hurley",     "y": "2012", "body_region": "knee",        "condition": "knee pain (chronic)",                   "country": "UK",          "study_design": "RCT", "perspective": "healthcare", "outcome_measure": "WOMAC",                          "outcome_type": "clinical", "time_horizon": "30 months"},
    {"a": "jessep",     "y": "2009", "body_region": "knee",        "condition": "knee pain (chronic)",                   "country": "UK",          "study_design": "RCT", "perspective": "healthcare", "outcome_measure": "QALY (EQ-5D)",                   "outcome_type": "QALY",     "time_horizon": "12 months"},
    {"a": "kigozi",     "y": "2018", "body_region": "knee",        "condition": "knee osteoarthritis",                   "country": "UK",          "study_design": "RCT", "perspective": "healthcare", "outcome_measure": "QALY (EQ-5D)",                   "outcome_type": "QALY",     "time_horizon": "18 months"},
    {"a": "knoop",      "y": "2023", "body_region": "knee",        "condition": "knee osteoarthritis",                   "country": "Netherlands", "study_design": "RCT", "perspective": "societal",   "outcome_measure": "QALY (EQ-5D)",                   "outcome_type": "QALY",     "time_horizon": "12 months"},
    {"a": "mccarthy",   "y": "2004", "body_region": "knee",        "condition": "knee osteoarthritis",                   "country": "UK",          "study_design": "RCT", "perspective": "healthcare", "outcome_measure": "QALY (EQ-5D)",                   "outcome_type": "QALY",     "time_horizon": "12 months"},
    {"a": "mitchell",   "y": "2005", "body_region": "knee",        "condition": "total knee replacement",                 "country": "UK",          "study_design": "RCT", "perspective": "healthcare", "outcome_measure": "SF-36, WOMAC",                   "outcome_type": "clinical", "time_horizon": "15 months"},
    {"a": "pryymachenko","y":"2021", "body_region": "knee",        "condition": "knee osteoarthritis",                   "country": "New Zealand", "study_design": "RCT", "perspective": "societal",   "outcome_measure": "QALY (EQ-5D)",                   "outcome_type": "QALY",     "time_horizon": "24 months"},
    {"a": "pryymachebko","y":"2021","body_region": "knee",        "condition": "knee osteoarthritis",                   "country": "New Zealand", "study_design": "RCT", "perspective": "societal",   "outcome_measure": "QALY (EQ-5D)",                   "outcome_type": "QALY",     "time_horizon": "24 months"},
    {"a": "rhon",       "y": "2022", "body_region": "knee",        "condition": "knee osteoarthritis",                   "country": "US",          "study_design": "RCT", "perspective": "healthcare", "outcome_measure": "QALY (EQ-5D)",                   "outcome_type": "QALY",     "time_horizon": "12 months"},
    {"a": "sevick",     "y": "2000", "body_region": "knee",        "condition": "knee osteoarthritis",                   "country": "US",          "study_design": "RCT", "perspective": "healthcare", "outcome_measure": "Disability score, stair climb, 6-min walk","outcome_type": "clinical","time_horizon": "18 months"},
    {"a": "sevick",     "y": "2009", "body_region": "knee",        "condition": "knee osteoarthritis",                   "country": "US",          "study_design": "RCT", "perspective": "healthcare", "outcome_measure": "WOMAC, stair climb, 6-min walk", "outcome_type": "clinical", "time_horizon": "18 months"},
    {"a": "stan",       "y": "2015", "body_region": "knee",        "condition": "knee osteoarthritis (varus deformity)", "country": "Romania",     "study_design": "controlled trial","perspective": "healthcare","outcome_measure": "QALY (EQ-5D)",             "outcome_type": "QALY",     "time_horizon": "unclear"},
    {"a": "tan",        "y": "2010", "body_region": "knee",        "condition": "patellofemoral pain syndrome",          "country": "Netherlands", "study_design": "RCT", "perspective": "societal",   "outcome_measure": "QALY (EQ-5D)",                   "outcome_type": "QALY",     "time_horizon": "12 months"},
    {"a": "tan",        "y": "2009", "body_region": "knee",        "condition": "patellofemoral pain syndrome",          "country": "Netherlands", "study_design": "RCT", "perspective": "societal",   "outcome_measure": "QALY (EQ-5D)",                   "outcome_type": "QALY",     "time_horizon": "12 months"},
    {"a": "graaf",      "y": "2020", "body_region": "knee",        "condition": "meniscal tear (non-obstructive)",       "country": "Netherlands", "study_design": "RCT", "perspective": "societal",   "outcome_measure": "IKDC, QALY (EQ-5D)",             "outcome_type": "both",     "time_horizon": "24 months"},
    {"a": "graaff",     "y": "2023", "body_region": "knee",        "condition": "meniscal tear (traumatic)",             "country": "Netherlands", "study_design": "RCT", "perspective": "societal",   "outcome_measure": "QALY (EQ-5D)",                   "outcome_type": "QALY",     "time_horizon": "24 months"},
    # ── LOWER LIMB MIXED ──────────────────────────────────────────────────
    {"a": "abbott",     "y": "2019", "body_region": "multi_region","condition": "hip and knee osteoarthritis",           "country": "New Zealand", "study_design": "RCT", "perspective": "societal",   "outcome_measure": "QALY (SF-6D)",                   "outcome_type": "QALY",     "time_horizon": "24 months"},
    {"a": "pinto",      "y": "2013", "body_region": "multi_region","condition": "hip and knee osteoarthritis",           "country": "New Zealand", "study_design": "RCT", "perspective": "societal",   "outcome_measure": "QALY (SF-12v2), WOMAC",          "outcome_type": "both",     "time_horizon": "12 months"},
    {"a": "bulthuis",   "y": "2008", "body_region": "multi_region","condition": "hip and knee osteoarthritis",           "country": "Netherlands", "study_design": "RCT", "perspective": "societal",   "outcome_measure": "Functional ability, MACTAR",     "outcome_type": "clinical", "time_horizon": "6 months"},
    {"a": "coupe",      "y": "2007", "body_region": "multi_region","condition": "hip and knee osteoarthritis",           "country": "Netherlands", "study_design": "RCT", "perspective": "societal",   "outcome_measure": "QALY (EQ-5D)",                   "outcome_type": "QALY",     "time_horizon": "15 months"},
    {"a": "fernandes",  "y": "2017", "body_region": "multi_region","condition": "hip and knee replacement",              "country": "Denmark",     "study_design": "RCT", "perspective": "healthcare", "outcome_measure": "HOOS, KOOS, QALY (EQ-5D)",       "outcome_type": "both",     "time_horizon": "12 months"},
    {"a": "lin",        "y": "2008", "body_region": "ankle",       "condition": "ankle fracture",                        "country": "Australia",   "study_design": "RCT", "perspective": "healthcare", "outcome_measure": "AQOL, LEFS",                     "outcome_type": "clinical", "time_horizon": "5-6 months"},
    # ── OTHER CONDITIONS ──────────────────────────────────────────────────
    {"a": "barnhoorn",  "y": "2018", "body_region": "other",       "condition": "complex regional pain syndrome type 1", "country": "Netherlands", "study_design": "RCT", "perspective": "healthcare", "outcome_measure": "QALY (EQ-5D)",                   "outcome_type": "QALY",     "time_horizon": "9 months"},
    {"a": "daker",      "y": "1999", "body_region": "multi_region","condition": "musculoskeletal problems",              "country": "UK",          "study_design": "RCT", "perspective": "healthcare", "outcome_measure": "SF-36, VAS",                     "outcome_type": "clinical", "time_horizon": "5-6 months"},
    {"a": "heij",       "y": "2022", "body_region": "other",       "condition": "mobility problems",                     "country": "Netherlands", "study_design": "RCT", "perspective": "healthcare", "outcome_measure": "QALY (EQ-5D)",                   "outcome_type": "QALY",     "time_horizon": "6 months"},
    {"a": "lilje",      "y": "2014", "body_region": "multi_region","condition": "mixed musculoskeletal (waiting list)",   "country": "Sweden",      "study_design": "RCT", "perspective": "healthcare", "outcome_measure": "QALY (SF-6D)",                   "outcome_type": "QALY",     "time_horizon": "12 months"},
    {"a": "hout",       "y": "2005", "body_region": "other",       "condition": "rheumatoid arthritis",                  "country": "Netherlands", "study_design": "RCT", "perspective": "societal",   "outcome_measure": "HAQ, MACTAR, QALY (EQ-5D)",      "outcome_type": "both",     "time_horizon": "24 months"},
]

CHECK_FIELDS = [
    "body_region", "country", "study_design",
    "perspective", "outcome_type", "outcome_measure", "time_horizon",
]

UNKNOWN_VALS = {"unknown", "unclear", "", "none", "na", "n/a"}
